services:
  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - backend
    volumes:
      - redis-data:/data
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - backend
networks:
  backend:
volumes:
  redis-data: